Repository mdziekon/UniEngine, pull requests merged in 2020-04, with the labels that each got.

#95 Refactor fleet missions' code | Part 04 | Morale modifiers calculation
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  modules/flights/_includes.php
  modules/flights/utils/calculations/calculatePillageFactor.utils.php
  modules/flights/utils/modifiers/calculateMoraleModifiers.utils.php
  modules/flights/utils/modifiers/index.php
Labels: pr:bugfix, pr:enhancement_request

#96 Refactor fleet missions' code | Part 05 | User technologies initialization
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  includes/vars_elementcategories.php
  modules/flights/_includes.php
  modules/flights/utils/initializers/index.php
  modules/flights/utils/initializers/technologies.utils.php
Labels: pr:enhancement_request

#97 Refactor fleet missions' code | Part 06 | User stats aggregation
  includes/functions/FlyingFleetHandler.php
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseExpedition.php
  includes/functions/MissionCaseGroupAttack.php
  includes/functions/MissionCaseMIP.php
  includes/functions/MissionCaseSpy.php
  includes/helpers/world/elements.common.functions.php
  modules/flights/_includes.php
  modules/flights/utils/calculations/calculateResourcesLoss.utils.php
  modules/flights/utils/fleetCache/updateUserStats.utils.php
  modules/flights/utils/initializers/userStats.utils.php
Labels: pr:bugfix, pr:enhancement_request

#98 Refactor fleet missions' code | Part 07 | Post-combat fleet updates
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  includes/helpers/fleets/functions.php
  modules/flights/_includes.php
  modules/flights/utils/calculations/calculatePillageStorage.utils.UETest.php
  modules/flights/utils/calculations/calculatePillageStorage.utils.php
  modules/flights/utils/factories/createFleetDevelopmentLogEntries.utils.php
  modules/flights/utils/factories/createFleetUpdateEntry.utils.php
  modules/flights/utils/factories/index.php
Labels: pr:enhancement_request

#100 Refactor fleet missions' code | Part 07 | Post-combat system messages
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  includes/helpers/common/collections.functions.php
  includes/helpers/common/navigation.functions.php
  modules/flights/_includes.php
  modules/flights/utils/factories/createCombatMessages.utils.php
  modules/flights/utils/helpers/hasLostAnyDefenseSystem.utils.php
  modules/flights/utils/helpers/index.php
Labels: pr:enhancement_request

#102 Refactor fleet missions' code | Part 09 | Defense systems rebuild
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  includes/helpers/common/collections.functions.php
  modules/flights/_includes.php
  modules/flights/utils/calculations/calculateUnitsRebuild.utils.php
Labels: pr:bugfix, pr:enhancement_request

#103 Updating lostpassword language files
  language/en/lostpassword.lang
  language/pl/lostpassword.lang
Labels: pr:enhancement_request

#106 Refactor fleet missions' code | Part 10 | Defenders' details aggregation
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  modules/flights/_includes.php
  modules/flights/utils/initializers/defenderDetails.utils.php
Labels: pr:enhancement_request

#107 Refactor fleet missions' code | Part 11 | Combat result stats aggregation
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  modules/flights/utils/fleetCache/updateUserStats.utils.php
Labels: pr:enhancement_request

#109 Update issue templates (add bug report tmpl)
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: pr:repo

#110 Refactor fleet missions' code | Part 12 | Combat morale updates
  includes/functions/MissionCaseAttack.php
  includes/functions/MissionCaseDestruction.php
  includes/functions/MissionCaseGroupAttack.php
  modules/flights/_includes.php
  modules/flights/utils/calculations/calculatePostCombatMorale.utils.php
  modules/flights/utils/calculations/calculatePostCombatMoraleUpdates.utils.php
  modules/flights/utils/factories/createCombatReportMoraleEntry.utils.php
  modules/flights/utils/fleetCache/morale.utils.php
Labels: pr:bugfix, pr:enhancement_request

#105 French translation | Part 1
  language/fr/aboutpro.lang
  language/fr/activate.lang
  language/fr/admin.lang
  language/fr/alliance.lang
  language/fr/attackslist.lang
  language/fr/banned.lang
  language/fr/bannedUser.lang
  language/fr/buddy.lang
  language/fr/buildings.lang
  language/fr/changelog.lang
  language/fr/chat.lang
  language/fr/common_vacationmode.lang
  language/fr/contact.lang
  language/fr/converter.lang
  language/fr/cookies.lang
  language/fr/leftmenu.lang
  language/fr/months.lang
  language/fr/overview.lang
  language/fr/profile.lang
  language/fr/search.lang
  language/fr/tasks_infobox.lang
  language/fr/tech.lang
  language/fr/texts.lang
  language/fr/topmenu.lang
Labels: pr:translation

#111 Fixed 2 translation errors in the english tasks.lang file
  language/en/tasks.lang
Labels: pr:bugfix, pr:first_contribution

#114 GH-112 | Fix tasks data handling upon completion
  includes/functions.php
Labels: pr:bugfix
